"""SOLVER.md generator (the provisioning solver's written report).

Sections follow the campaign brief (deliverable C): problem statement as a
constrained optimisation, method, Pareto frontier + knees, break-even
surface reading with worked "for X traffic, provision Y" examples,
sensitivity (COMPUTE_EFF / t_0 AND the dense-price ambiguity), limitations,
and the explicit disagreement table vs the theory layer.
"""
from __future__ import annotations

import math
from typing import Dict, List

from .. import paths
from .model import (DENSE_PRICE_READINGS, SOLVE_CORES, SOLVE_DENSE_PRICE_GPU_S,
                    SOLVE_DENSE_PRICE_GPU_S_CHEAP, SOLVE_RHO_MAX, SolveModel)

OUT_MD = paths.THEORY_DIR / "solve" / "SOLVER.md"


def _f(x, nd=3) -> str:
    if x is None or x == "":
        return "-"
    if isinstance(x, str):
        return x
    if isinstance(x, float) and not math.isfinite(x):
        return "inf"
    return ("%%.%dg" % nd) % x


def write_solver_md(out: dict, sm: SolveModel) -> None:
    knees = out["knees"]
    be = out["breakeven_summary"]
    sens = out["sensitivity_summary"]
    prov = out["provisioning"]
    prov_bad = out["provisioning_infeasible"]
    disag = out["disagreement"]
    cont = out["contour"]

    L: List[str] = []
    A = L.append
    A("# SOLVER.md — the dee-serve capacity planner (Phase-7 component C)")
    A("")
    A("Minimum-cost provisioning over the dee hierarchy, stated as a "
      "constrained optimisation and solved by enumeration over the "
      "discrete cell grid with closed-form memory sizing. Generated by "
      "`python -m theory.run_all solve` (deterministic, no RNG); code in "
      "`theory/solve/` (`model`, `pareto`, `surfaces`, `provisioning`, "
      "`report`).")
    A("")
    A("## 0. The problem, stated")
    A("")
    A("```")
    A("minimise    $/1k tok = 1000 * (r * replica_rate_s + volume_rate_s) "
      "/ (lambda * L)")
    A("over        cell (discrete: constants.ALL_CELLS), host GiB "
      "(continuous, 17-point grid 4-1024), VRAM GiB (continuous within "
      "card memory, 4 fractions),")
    A("            prefetch budget {hints off, one measured legal hint "
      "budget}, batch policy b (grid), replicas r (integer, <= 4096)")
    A("subject to  Poisson arrivals lambda, request shape L (SERVE_ASSUMPTIONS: "
      "512 decode tokens), per-stream decode SLO (5 / 20 / 50 tok/s),")
    A("            host/VRAM memory <= cell limits, storage bandwidth of "
      "the cell, rho <= %.2f headroom (SOLVE_RHO_MAX) + batch-fillability,"
      % SOLVE_RHO_MAX.value)
    A("            the exactness contract: a wrong prefetch hint may only "
      "waste bandwidth, never change execution")
    A("```")
    A("")
    A("Named methods only: enumeration; Che's common-TTL residence model "
      "(THEORY.md 3.1) with the two-level miss-through form (5.1); the "
      "overlap-corrected token roofline `T_pred` (5.1); Little's law; an "
      "M/M/1 response-time inflation with a Kleinrock batch-fillability "
      "window; the batch-overlap correction `u_i(b) = 1-(1-pi_i)^b`. "
      "Every constant is tagged in [`../data/provenance.csv`](../data/"
      "provenance.csv).")

    A("")
    A("## 1. Pareto frontier and the knee allocations")
    A("")
    A("`data/solve_pareto.csv` (all enumerated points, dominated points "
      "flagged not dropped), `data/solve_knees.json`, "
      "[`../figs/solve_pareto.png`](../figs/solve_pareto.png). Knee = "
      "kneedle-style max perpendicular distance from the frontier chord in "
      "(log TPS, log $/1k-tok) space (SOLVE_KNEE_METHOD).")
    A("")
    A("| model | knee cell | host GiB | VRAM GiB | b | tok/s | $/1k tok "
      "| dense (computed price) | ratio | limiter |")
    A("|---|---|---:|---:|---:|---:|---:|---:|---:|---|")
    for k in knees:
        if not k.get("tps_capacity"):
            continue
        A("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            k["model"], k.get("cell", "-"), _f(k.get("host_gib")),
            _f(k.get("vram_gib")), _f(k.get("batch")), _f(k["tps_capacity"]),
            _f(k.get("usd_per_1k_tok")),
            _f(k.get("dense_cost_usd_per_1k_tok")),
            _f(k.get("ratio_knee_over_dense")), k.get("limiter", "-")))
    A("")
    A("Line items (GPU + CPU + RAM + volume) per knee are in "
      "`data/solve_knees.json` `provisioning_line_item`. The 2xT4 row is "
      "NOT purchasable (price table carries T4 = 0; `is_purchasable=false` "
      "in the CSV) — its break-even per-GPU price is computed in the JSON "
      "(SOLVE_T4_PRICE_ARTIFACT).")
    pf_notes = [k for k in knees if k.get("prefetch_arm_penalty")]
    if pf_notes:
        A("")
        A("Prefetch lever at the knee (hints off vs the measured m=1 "
          "arm): " + "; ".join(
              "%s tps x%.3f, cost x%.3f (t_pf %.3f s/tok)" % (
                  p["model"],
                  p["prefetch_arm_penalty"]["tps_ratio_m1_over_off"],
                  p["prefetch_arm_penalty"]["cost_ratio_m1_over_off"],
                  p["prefetch_arm_penalty"]["t_pf_s_per_tok"])
              for p in pf_notes) + " — consistent with P12 (lead-1 hints "
              "worth ~0 s).")

    A("")
    A("## 2. Break-even surface vs the dense-residency baseline")
    A("")
    A("`data/solve_breakeven_surface.csv` (per (model, L, lambda, price "
      "reading) row), `data/solve_breakeven_contour.csv` (ratio = 1.0 "
      "crossings), [`../figs/solve_breakeven.png`](../figs/solve_breakeven.png).")
    A("")
    A("**Dense-price ambiguity carried through everything** (Phase-7 "
      "correction; THEORY.md 6 disclosure): the DENSE_BASELINE constant is "
      "computed at `0.003223 $/GPU/s` = **$11.60/GPU/h** but its note says "
      "**$3.223/GPU/h** (3.223/1000 vs 3.223/3600). Dense $/1k tok: "
      "$%.4f (computed) vs $%.4f (cheap) — **3.57x**. Every conclusion "
      "below states its reading." % (
          sm.dense_by_reading["computed_0.003223"]["dsv4_flash"]
          .cost_usd_per_1k_tok(),
          sm.dense_by_reading["cheap_0.000895"]["dsv4_flash"]
          .cost_usd_per_1k_tok()))
    A("")
    A("### Verdict grid (dee wins where ratio < 1)")
    A("")
    A("| model | L | price reading | dee wins for | ratio @ 1 req/s | "
      "verdict |")
    A("|---|---:|---|---|---:|---|")
    for s in be["rows"]:
        A("| %s | %g | %s | %s | %s | %s |" % (
            s["model"], s["L_req"], s["price_reading"],
            ("lambda <= %s req/s" % _f(s["max_lam_dee_wins"]))
            if s["dee_wins_anywhere"] else "never",
            _f(s["ratio_at_ref_lam1"]), s["verdict"]))
    A("")
    if cont:
        A("Break-even contour points (lambda where dee/dense = 1.0, "
          "log-lambda interpolation between grid points; full table in "
          "`data/solve_breakeven_contour.csv`):")
        A("")
        A("| model | L | price reading | lambda* req/s |")
        A("|---|---:|---|---:|")
        for c in cont[:24]:
            A("| %s | %g | %s | %s |" % (
                c["model"], c["L_req"], c["price_reading"],
                _f(c["lambda_breakeven"])))
        if len(cont) > 24:
            A("| ... | (%d more rows in the CSV) | | |" % (len(cont) - 24))

    A("")
    A("### \"For X traffic, provision Y\" — worked examples")
    A("")
    A("From `data/solve_provisioning.csv` (512-token requests; the "
      "examples below are the rows nearest 0.1 / 1 / 10 req/s at "
      "SLO 20 tok/s):")
    A("")
    A("| traffic | model | provision (cell x host x VRAM x replicas) "
      "| tok/s delivered | $/1k tok | ratio (computed price) |")
    A("|---|---|---|---:|---:|---:|")
    for lam in (0.1, 1.0, 10.0):
        for m in sorted(sm.geoms):
            row = next((r for r in prov
                        if abs(r["lambda_req_s"] - lam) < 1e-9
                        and r["slo_tok_s"] == 20.0 and r["model"] == m),
                       None)
            if row is None:
                A("| %.1f req/s | %s | INFEASIBLE at SLO 20 | - | - | - |"
                  % (lam, m))
                continue
            A("| %.1f req/s | %s | %s x %.0f GiB x %.1f GiB x %d "
              "| %s | %s | %s |" % (
                  lam, m, row["cell"], row["host_gib"], row["vram_gib"],
                  row["replicas"], _f(row["tps_capacity"]),
                  _f(row["usd_per_1k_tok"]),
                  _f(row["ratio_vs_dense_computed"])))
    if prov_bad:
        A("")
        n_tot = len(prov) + len(prov_bad)
        A("%d/%d (model, lambda, SLO) cells are infeasible at rho<=0.7 "
          "with the batch-fillability window (full list: "
          "`data/solve_provisioning_infeasible.csv`)." % (len(prov_bad),
                                                         n_tot))
        if len(prov_bad) == n_tot:
            A("**Every (model, lambda, SLO) combination is infeasible** — "
              "the per-stream decode SLO (>= 5 tok/s/stream) exceeds what "
              "any bounded cell delivers per stream: feasibility needs "
              "X/b >= slo/(1-rho), i.e. >= ~16.7 tok/s per stream at "
              "SLO=5, while b=1 per-replica rates top out at ~3-8 tok/s "
              "on the enumerated cells. Replication scales aggregate "
              "throughput but cannot raise a stream's own rate. dee-serve "
              "is a cost/throughput play at batch; it cannot promise "
              "per-stream decode speed at these SLOs — consistent with "
              "P15c's no-cell-wins-at-b=1.")

    A("")
    A("## 3. Sensitivity — the two weakest constants and the price reading")
    A("")
    A("`data/solve_sensitivity.csv`, "
      "[`../figs/solve_sensitivity.png`](../figs/solve_sensitivity.png). "
      "Each scenario re-solves the min-cost deployment at lambda=1 req/s, "
      "L=512, SLO=20 under (COMPUTE_EFF, t_0) = %s." % ", ".join(
          "(%s: eff %.2f, t0 %.0f us)" % (n, e, t)
          for n, e, t in (("eff06_t387", 0.6, 387.0),
                          ("eff03_t50", 0.3, 50.0),
                          ("eff08_t50", 0.8, 50.0),
                          ("eff03_t400", 0.3, 400.0),
                          ("eff08_t400", 0.8, 400.0))))
    A("")
    flips = sens.get("flips", [])
    if flips:
        A("Headline moves (verdict flips and infeasibilities):")
        A("")
        for fl in flips:
            A("- **%s / %s (%s):** %s" % (fl["model"], fl["price_reading"],
                                          fl["scenario"], fl["flip"]))
    else:
        A("No verdict flips across the scenario grid at the reference "
          "traffic — the recommendation is robust to (COMPUTE_EFF, t_0) "
          "there.")
    A("")
    A("The dense-price reading dominates every compute constant: it is a "
      "**3.57x** move on the competitor's cost, while COMPUTE_EFF "
      "0.3-0.8 moves dee's compute-bound TPS by at most ~2.7x on "
      "compute-bound cells and little on storage/H2D-bound ones "
      "(THEORY.md 8 elasticities). **A product decision must resolve the "
      "H100 price first.**")

    A("")
    A("## 4. Limitations (dominant ASSUMPTIONS)")
    A("")
    A("1. `COMPUTE_EFF = 0.6` of vendor dense-tensor peak (range 0.3-0.8) "
      "and the anchor-calibrated per-touch cost `t_0 = 387 us` (FALSIFICATION "
      "assumptions 1 and 7) — no in-repo GPU microbenchmark (data needed).")
    A("2. **The dense-price ambiguity** above — unresolved, 3.57x, and it "
      "flips the break-even.")
    A("3. `SOLVE_CORES = 2` CPU cores per replica (ASSUMPTION 1-4) vs "
      "serving.py's full-cell billing — see the disagreement table.")
    A("4. Popularity-shape transfer (S_TRANSFER) for the non-DSv4 stores; "
      "the MiMo/MiniMax frontiers inherit DSv4-Flash's locality (data "
      "needed: per-model router traces).")
    A("5. The dense baseline's 200 tok/s achieved decode and the "
      "SOLVE_DENSE_SCALE throughput law (dense throughput does NOT fall "
      "with resident footprint) are deliberately conservative toward the "
      "competitor.")
    A("6. `rho_fill` batch-fillability (Kleinrock K >= b-1) is a modeling "
      "convention for continuous batching; no measured scheduler exists.")

    A("")
    A("## 5. Disagreements with the theory layer (quantified)")
    A("")
    A("`data/solve_disagreement.csv`. The prior hand-computed frontier "
      "(THEORY.md 6, `data/serve_cost_frontier.csv`) is compared point for "
      "point; differences arise from (a) batch policy snap (serving.py's "
      "b=8 rows vs the solver's batch-fillability window), (b) the "
      "SOLVE_CORES accounting, (c) volume amortisation at r=1. Nothing is "
      "reconciled silently:")
    A("")
    A("| quantity | theory | solver | rel delta | note |")
    A("|---|---:|---:|---:|---|")
    for d in disag[:30]:
        A("| %s | %s | %s | %s | %s |" % (
            d["quantity"], _f(d["theory_value"]), _f(d["solver_value"]),
            ("%+.1f%%" % (100.0 * d["rel_delta"]))
            if isinstance(d["rel_delta"], float) and d["rel_delta"] != ""
            else "-", d["note"]))
    if len(disag) > 30:
        A("| ... | (%d more rows in the CSV) | | | |" % (len(disag) - 30))
    A("")
    A("---")
    A("")
    A("*Generated by `theory/solve/report.py`; regenerate with "
      "`python -m theory.run_all solve` from `dee.cpp/theory/`.*")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(L) + "\n", encoding="utf-8")
